### ISSUE TITLE
desc files: templates

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#103]
provide standard templates for controllers like
Joysticks, GamePads, MIDI keyboards, HID keyboards etc.
since will have more or less the same elements, regardless of vendors.

**Comment by adcxyz** [comment]
"since will have more or less the same elements, regardless of vendors."
does this also mean they will have the same button numbers etc? 
In any case, this should be easier now with parentDesc files. 
they could be made to inherit the description as well, 
and then only overwrite the things that are different from the defaults.

**Comment by adcxyz** [comment]
There has been a generic descfile for mouse for a while now, and matching to it works.
could be used as a model for joysticks, gamepads etc if those are really needed.

**Comment by adcxyz** [comment]
discussion seems to have ended, so closing.
