### ISSUE TITLE
documented interface for adding/removing elements to MKtl

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#146]
For incrementally building an MKtl.

**Comment by adcxyz** [comment]
actually since we can rebuild MKtls flexibly from descs/dicts, adding elements to the basic element hierarchy has become unnecessary. Creating additional groups of existing elements and derived elements is also easy already, and they can be added to collectives until there is a final design for free groups.

**Comment by adcxyz** [comment]
based on above reasoning, closing this for now.
