### ISSUE TITLE
fix website controller page template so that MKtlDesc(\rnnd0).web; works

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#204]
should point to remote webpage:

```
"http://modalityteam.github.io/controllers/%.html".format(descFilename.strip(".desc.scd"))
```

**Comment by adcxyz** [comment]
mostly done: 
MKtlDesc.web; // works
m = MKtlDesc('APCMINI'); 
m.web // not working because of changed name

// this opens the url, but WebView closes very quickly 
// Qt WebView exits apparently because of incompatible html file?

MKtlDesc.web("akai-apcmini"); 

btw, all the desc names now have minuses ("akai-apcmini"), 
can we switch that to underscores? 
then writing the as Symbols with \name works - \akai_apcmini

**Comment by adcxyz** [comment]
MKtlDesc.web; // works
MKtlDesc.allDescs.choose.web // still auto-closes

looks like this has to be fixed in html files. till ?

**Comment by LFSaw** [comment]
WebView-autoclose works now. See supercollider/supercollider#1505

**Comment by adcxyz** [comment]
with a spanking fresh build only, or with say 3.6.6 IDE as well?

**Comment by LFSaw** [comment]
spanking... :/

I also now ( d8306ad ) added a ```docURI``` method to MKtlDesc and changed naming for ```Meta_MKtlDesc:webhome``` to ```docURI``` because: clarity.
