### ISSUE TITLE
are collectives working again?

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#230]
This is essential for many OSC usecases.

**Comment by LFSaw** [comment]
short answer: not yet.

long answer:

As I understand, collectives never really worked flawlessy in all possible scenarios. So this needs more discussion and careful planning (and implementation).
Before investing more time and effort in new ideas and features, I'd like to first make the merge/move of the refactor2 branch to master 
As it seems that there are currently mainly two people involved in the programming process of making things work in the refactor, our approach is to merge/move first and, by this, give people the opportunity to add features in small steps (by branching/discussing/merging) rather than large ones (IMHO the refactor branch somehow escaped the "small steps"-paradigm and this should be prevented in the future...).
By that we can assure to keep everyone involved in the development of what will be known as the master branch.

**Comment by LFSaw** [comment]
implemented and tested in a5f7a1c.
