### ISSUE TITLE
what is the status of MKltGUI?

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#231]

**Comment by LFSaw** [comment]
should just work... @adcxyz ?

**Comment by adcxyz** [comment]
short answer: yes. 

long answer: 

// here is a test: 
MKtlDesc.loadDescs; 
MKtlDesc.allDescs.size;  // 47

MKtlDesc.allDescs.do { |desc| 
	try { MKtl(desc.fullDesc.filename, desc) } { desc.postln } }; "";

MKtl.all.size; // 47 

n = 0;
MKtl.all.do { |mk| try { mk.gui; n = n + 1 } { mk.postln } };
n // 47

Looking at them and trying them, they seem all  ok and functional. 

Some of the handwritten desc dicts in the How to create an <XYZ> description files series are not working yet.
This is likely because the refactor is a bit stricter with how it determines whether a dict in a desc is an elementdescription
or not (needed for nested element lists), so those desc dicts will need adding some required keys. 

best a

**Comment by LFSaw** [comment]
Actually, we just remembered that the new GUI is not (yet) accessible via ```Mktl.gui```, so the example code is:


```
MKtlDesc.loadDescs; 
MKtlDesc.allDescs.size; // 47 

MKtlDesc.allDescs.do { |desc| try { MKtl(desc.fullDesc.filename, desc) } { desc.postln } }; ""; 

MKtlDesc.allDescs.size == MKtl.all.size;
// -> true

n = 0; MKtl.all.do { |mk| try { MKtlGUI(mktl: mk); n = n + 1 } { mk.postln } }; n // 47
```
