### ISSUE TITLE
MKtl:rebuild -- MKtlDesc - dict is not a valid description

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#253]
In ```Tutorials/How_to_create_a_description_file_for_MIDI.schelp```, near 

> As a first example, we now create an MKtl containing exactly one MKtlElement that responds to a noteOn event. For mapping its velocity we use the spec: \midiVel identifier, which tells the system to normalise the raw value range of velocity values (0 to 127) to values between 0 and 1.

it says:

```
// on OSX, does not work yet to build a proper device like this
MKtlLookup.all;
m = MKtl( \testMIDI, ~descInput );
m.rebuild( ~descInput ); // later, one can update it
```
When evaluating, I get:

```
WARNING: MKtlDesc - dict is not a valid description: ( 'elementsDesc': ( 'elements': [ ( 'midiChan': 0, 'key': pkey, 'spec': midiVel, 'type': pianoKey, 
  'ioType': in, 'midiNum': 64, 'midiMsgType': noteOn ) ] ), 'filename': testMIDI, 'protocol': midi )
MKtl:finishInit: no desc given, cannot create elements.
// Maybe you want to explore this device with:
MKtl('testMIDI').explore;
MKtldevice.open: parentMktl.desc.isNil - should not happen!
MKtl('testMIDI').openDevice: remaining virtual.
```

(on 64353a802ec8819cf0125d23f269bb772c32670b )

**Comment by adcxyz** [comment]
From above in the same file: 
So you can test the examples below even without a physical device, we will use SuperCollider's own input and output. In order to do that, you will need to do different things depending on which platform you are using.
On OSX, please go to Audio MIDI Setup, and create an IAC Bus you can use.

... 
Then you can continue here:
